# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac7c0ab430b48b344b9e28d438728a101291e02bc44337a89162ed7e0d4ff1b2f439b5e3409d51549ac59e7629bbd2669d39e03a417cb6e2ddd6c9931de477da

test:
  secret_key_base: 78d19402eb4f9009668a2849d8f3f008e42e3966d59bd16a9d0d75864ee9de44f790677cfbc2725d34987fc81feb9dce6eb1234b9adcbad35b44a744d549962b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
